---
driver:
    name: vagrant
      # This VM Spec emulates a raspberry pi 1 B on my late 2013 MBP
      # customize:
      #   audio: coreaudio
      #   audiocontroller: hda
      #   memory: 768
      #   cpus: 1
#   cpuexecutioncap: 25
#    customize:
#      memory: 2048
#      cpus: 4
#      cpuexecutioncap: 80
#      usb: 'on'
#      usbehci: 'on'
#      audio: alsa
#      audioout: 'on'

    synced_folders:
      - ["data/%{instance_name}", "/opt/xfer", "create: true"]

#driver:
#  name: docker

provisioner:
  name: ansible_playbook
  roles_path: roles
  hosts: all
  playbook: site.yml
  require_ansible_repo: false
  require_ansible_omnibus: true
  ansible_verbose: true
  ansible_verbosity: 3
  require_chef_for_busser: false
  extra_vars:
    redis_server: 172.16.192.10
    redis_port: 6379
    use_apt_cacher: False
    apt_cacher: 127.0.0.1
    hobbit_server: 127.0.0.1
    no_autogen_bbhosts: True

platforms:
- name: ubuntu-20.04
  driver_config:
    box: generic/ubuntu2004

suites:
- name: scanner
  provisioner:
    hosts: scanner
  driver_config:
    network:
      - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: false}]
      - ["forwarded_port", { guest: 8000, host: 8000, auto_correct: false}]
#      - ["private_network", {ip: "172.16.192.10"}]

- name: foo
  provisioner:
    hosts: all
